use std::env;
use std::fs;
use std::path::PathBuf;

/// Embed the shared backend app secret (`X-API-Key`) at build time.
///
/// Set `MINITI_API_KEY` in the environment when building a release that should
/// support managed mode. The value is XOR-obfuscated with a build-random mask
/// so the literal never appears in the binary (`strings`), matching the other
/// clients. This is obfuscation, not security. When the variable is absent the
/// build has no key and managed mode reports itself unavailable at runtime —
/// BYOK still works. Nothing secret is ever written into the repo.
fn embed_api_key() {
    println!("cargo:rerun-if-env-changed=MINITI_API_KEY");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let key = env::var("MINITI_API_KEY").unwrap_or_default();

    let (obf, mask): (Vec<u8>, Vec<u8>) = if key.is_empty() {
        (Vec::new(), Vec::new())
    } else {
        // Deterministic per-build mask derived from the key + build hash so
        // repeated builds are reproducible without a fixed mask in source.
        let seed = format!("{}:{}", key, env::var("CARGO_PKG_VERSION").unwrap_or_default());
        let mut h: u64 = 0xcbf2_9ce4_8422_2325;
        for b in seed.bytes() {
            h ^= b as u64;
            h = h.wrapping_mul(0x0100_0000_01b3);
        }
        let mut mask = Vec::with_capacity(32);
        let mut x = h;
        for _ in 0..32 {
            x ^= x << 13;
            x ^= x >> 7;
            x ^= x << 17;
            mask.push((x & 0xff) as u8);
        }
        let obf = key
            .bytes()
            .enumerate()
            .map(|(i, b)| b ^ mask[i % mask.len()])
            .collect();
        (obf, mask)
    };

    let src = format!(
        "/// Generated by build.rs — do not edit.\npub const API_KEY_OBF: &[u8] = &{obf:?};\npub const API_KEY_MASK: &[u8] = &{mask:?};\n"
    );
    fs::write(out_dir.join("api_key.rs"), src).expect("write api_key.rs");
}

fn main() {
    embed_api_key();
    tauri_build::build()
}
